[build]
  functions = "functions"
  command = "npm run build"
  publish = "dist"

[dev]
  functionsPort = 3000
  autoLaunch = false
  command = "cross-env NODE_ENV=development webpack-dev-server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
